POST http://localhost:3003/auth
Content-Type: application/json

{
    "email": "qa.e1.p0@example.com",
    "password": "P@ssword123"
}

###

# Login — employee em VACATION (loginCapable)
POST http://localhost:3003/auth
Content-Type: application/json

{
    "email": "qa.vacation@example.com",
    "password": "P@ssword123"
}

###

# Request password reset
POST http://localhost:3003/auth/password-reset
Content-Type: application/json

{
    "email": "graubarberclub@gmail.com"
} 